services:
  restofrigo-landing:
    image: nginx:stable-alpine3.21
    container_name: restofrigo-landing
    restart: unless-stopped
    volumes:
      - ./src/:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=restofrigo.com,www.restofrigo.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=restofrigo.com,www.restofrigo.com
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "25M"

networks:
  proxy:
    name: proxy
    external: true
